spring:
  data:
    redis:
      port: 6379
      host: redis.ticketone.site
  application:
    name: broker # Eureka에 등록될 서비스의 고유 이름

eureka:
  client:
    service-url:
      defaultZone: http://eureka.ticketone.site:8761/eureka/ # Eureka 서버 주소
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
custom:
  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  events:
    url: http://app.ticketone.site:9000

server:
  port: 0
  tomcat:
    threads:
      # 동시에 처리할 수 있는 최대 스레드 수. 기본값 200.
      # DB 커넥션 풀과 마찬가지로 400 ~ 500 정도로 증설을 고려합니다.
      max: 500
    # 연결 요청을 대기열에 쌓아둘 수 있는 최대 수
    accept-count: 100
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
