spring:
  config:
    activate:
      on-profile: prod

filter:
  whitelist:
    urls:
      - method: "*"
        url: "/api/v1/auth/register"
      - method: "*"
        url: "/api/v1/auth/login"
      - method: "*"
        url: "/api/v1/auth/social/**"
      - method: "*"
        url: "/api/v1/events/list"
