server:
  port: 8080 # 게이트웨이는 8080 포트에서 실행됩니다.
  netty:
    connection-timeout: 30s
    max-connections: 2000
  reactor:
    netty:
      pool:
        max-connections: 2000
        max-idle-time: 30s


spring:
  application:
    name: api-gateway
  config:
    import:
      - optional:classpath:/application-secret.yml
      - optional:classpath:/application-gateway-routes-local.yml
      - optional:classpath:/application-gateway-routes-prod.yml
      - optional:classpath:/application-whitelist-local.yml
      - optional:classpath:/application-whitelist-prod.yml
  cloud:
    gateway:
      httpclient:
        max-header-size: 16KB
        max-initial-line-length: 4KB
        pool:
          max-connections: 2000
          acquire-timeout: 30000

springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth
        display-name: "Auth Service"
      - name: event
        url: /v3/api-docs/event
        display-name: "Event Service"
      - name: purchase
        url: /v3/api-docs/purchase
        display-name: "Purchase Service"
      - name: user
        url: /v3/api-docs/user
        display-name: "User Service"
      - name: seat
        url: /v3/api-docs/seat
        display-name: "Seat Service"
      - name: broker
        url: /v3/api-docs/broker
        display-name: "Broker Service"
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
