spring:
  datasource:
    hikari:
      maximum-pool-size: 1000
    url: jdbc:mysql://mysql.app.ticketone.site:3306?serverTimeZone=Asia/Seoul
    username: jiwoo
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
  h2:
    console:
      enabled: true
server:
  port: 9000
  tomcat:
    threads:
      max: 1100
  error:
    include-stacktrace: never

services:
  event:
    base-url: http://localhost:9002
  seat:
    base-url: http://localhost:9005

