custom:
  cookie:
    domain: .ticketon.site

server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://mysql.auth.ticketone.site:3306/auth?serverTimezone=Asia/Seoul
    username: jiwoo
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
